# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lux and Arbor Developments
email: martin@luxandarbor.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the homepage for Lux and Arbor Development. We are a young and ambitious company looking to
  help you create the software experiences you always dreamed of.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://luxandarbor.co.uk" # the base hostname & protocol for your site
twitter_username: MartinLandA19
github_username:  mshinebaum

# Build settings
markdown: kramdown
